export enum FigureLabel {
  GroupBasic = 'GroupBasic',
  GroupSimplePositionChange = 'GroupSimplePositionChange',
  GroupSimpleWomanTurn = 'GroupSimpleWomanTurn',
  GroupSimpleManTurn = 'GroupSimpleManTurn',
  GroupSimpleSimultaneousTurn = 'GroupSimpleSimultaneousTurn',

  PeriodOneToFour = 'PeriodOneToFour',
  PeriodFiveToEight = 'PeriodFiveToEight',

  TurnWomanTurn = 'TurnWomanTurn',
  TurnWomanSpin = 'TurnWomanSpin',
  TurnManTurn = 'TurnManTurn',
  TurnManSpin = 'TurnManSpin',
  TurnWomanCw = 'TurnWomanCw',
  TurnWomanCcw = 'TurnWomanCcw',
  TurnManCw = 'TurnManCw',
  TurnManCcw = 'TurnManCcw',
  TurnWomanDegrees90 = 'TurnWomanDegrees90',
  TurnWomanDegrees180 = 'TurnWomanDegrees180',
  TurnWomanDegrees270 = 'TurnWomanDegrees270',
  TurnWomanDegrees360 = 'TurnWomanDegrees360',
  TurnWomanDegrees450 = 'TurnWomanDegrees450',
  TurnWomanDegrees540 = 'TurnWomanDegrees540',
  TurnWomanDegrees630 = 'TurnWomanDegrees630',
  TurnWomanDegrees720 = 'TurnWomanDegrees720',
  TurnManDegrees90 = 'TurnManDegrees90',
  TurnManDegrees180 = 'TurnManDegrees180',
  TurnManDegrees270 = 'TurnManDegrees270',
  TurnManDegrees360 = 'TurnManDegrees360',
  TurnManDegrees450 = 'TurnManDegrees450',
  TurnManDegrees540 = 'TurnManDegrees540',
  TurnManDegrees630 = 'TurnManDegrees630',
  TurnManDegrees720 = 'TurnManDegrees720'
}

export const MAP_FIGURE_LABEL_TO_TEXT = new Map<FigureLabel, string>([
  [FigureLabel.GroupBasic, 'Basic'],
  [FigureLabel.GroupSimplePositionChange, 'Simple Position Change'],
  [FigureLabel.GroupSimpleWomanTurn, 'Simple W Turn'],
  [FigureLabel.GroupSimpleManTurn, 'Simple M Turn'],
  [FigureLabel.GroupSimpleSimultaneousTurn, 'Simple Simultaneous Turn'],

  [FigureLabel.PeriodOneToFour, '1-4'],
  [FigureLabel.PeriodFiveToEight, '5-8'],

  [FigureLabel.TurnWomanTurn, 'W Turn'],
  [FigureLabel.TurnWomanSpin, 'W Spin'],
  [FigureLabel.TurnManTurn, 'M Turn'],
  [FigureLabel.TurnManSpin, 'M Spin'],
  [FigureLabel.TurnWomanCw, 'W CW'],
  [FigureLabel.TurnWomanCcw, 'W CCW'],
  [FigureLabel.TurnManCw, 'M CW'],
  [FigureLabel.TurnManCcw, 'M CCW'],
  [FigureLabel.TurnWomanDegrees90, 'W 90\u00B0'],
  [FigureLabel.TurnWomanDegrees180, 'W 180\u00B0'],
  [FigureLabel.TurnWomanDegrees270, 'W 270\u00B0'],
  [FigureLabel.TurnWomanDegrees360, 'W 360\u00B0'],
  [FigureLabel.TurnWomanDegrees450, 'W 450\u00B0'],
  [FigureLabel.TurnWomanDegrees540, 'W 540\u00B0'],
  [FigureLabel.TurnWomanDegrees630, 'W 630\u00B0'],
  [FigureLabel.TurnWomanDegrees720, 'W 720\u00B0'],
  [FigureLabel.TurnManDegrees90, 'M 90\u00B0'],
  [FigureLabel.TurnManDegrees180, 'M 180\u00B0'],
  [FigureLabel.TurnManDegrees270, 'M 270\u00B0'],
  [FigureLabel.TurnManDegrees360, 'M 360\u00B0'],
  [FigureLabel.TurnManDegrees450, 'M 450\u00B0'],
  [FigureLabel.TurnManDegrees540, 'M 540\u00B0'],
  [FigureLabel.TurnManDegrees630, 'M 630\u00B0'],
  [FigureLabel.TurnManDegrees720, 'M 720\u00B0']
]);
